apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysecureshell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysecureshell
  template:
    metadata:
      labels:
        app: mysecureshell
    spec:
      containers:
      - name: mysecureshell
        image: registry.kyso.io/docker/mysecureshell:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        securityContext:
          capabilities:
            add:
            - IPC_OWNER
        env:
        - name: MYSSH_SFTP_UID
          value: '2020'
        - name: MYSSH_SFTP_GID
          value: '2020'
        - name: MYSSH_SECRET_NAME
          value: mysecureshell-secrets
        - name: MYSSH_HOST_KEYS
          value: host_keys.txt
        - name: MYSSH_USER_KEYS
          value: user_keys.txt
        - name: MYSSH_USER_PASS
          value: user_pass.txt
        - name: MYSSH_USER_SIDS
          value: user_sids.tgz
        volumeMounts:
        - mountPath: /fileSecrets
          name: mysecureshell-filesecrets
          readOnly: true
        - mountPath: /sftp
          name: mysecureshell-sftpdir
      volumes:
      - name: mysecureshell-filesecrets
        secret:
          secretName: mysecureshell-secrets
      - name: mysecureshell-sftpdir
        persistentVolumeClaim:
          claimName: mysecureshell
---
apiVersion: v1
kind: Service
metadata:
  name: mysecureshell
spec:
  ports:
  - port: 2020
    protocol: TCP
    targetPort: 22
  selector:
    app: mysecureshell
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysecureshell
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
